name: default

on:
  push:
    branches:
      - master
      - sdl
  pull_request:
    branches:
      - master
      - sdl

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: clean
      run: make clean
    - name: make
      run: make
