name: default

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: make_def
      run: make
    - name: clean_def
      run: make clean
    - name: conf_elks
      run: cp config-elks.mk config.mk
    - name: make_elks
      run: make
    - name: clean_elks
      run: make clean
    - name: conf_advtech
      run: cp config-advtech.mk config.mk
    - name: make_advtech
      run: make
    - name: clean_advtech
      run: make clean
